### ISSUE TITLE
RG35XX 2024 cannot use external Wi-Fi dongle due to wrong NetworkInterfaceBlacklist

### ISSUE THREAD

**Issue by FrnkPsycho** [knulli-cfw/distribution#108]
### Knulli build version

20240721

### Your architecture

RG35XX 2024

### Issue description

In connman config file `/etc/connman/main.conf` There is a line: `NetworkInterfaceBlacklist = wlan0,p2p...` and I found that external USB dongle's default interface is wlan0 which leads to unavailable wifi. I checkout the source code and found that it is because knulli didn't seperate rg35xxplus and rg35xx2024 so on plus it blocked wlan0 for internal wifi adapter (maybe) but for 2024 you need a external adapter which is allocated to wlan0.

Hope you guys look into this problem, maybe seperate 2024 from plus or allocate external dongle to `wlan1` or else?

### Detailed reproduction steps

I connected a custom built RTL8192CU Wi-Fi adapter with a usba to usbc connector to RG35XX 2024 and it's not working. The indicator LED didn't even on let alone flashing.

### Details of any attempts to fix this yourself

My current workaround is creating a system/custom.sh file on sdcard (system is in the same folder with bios / roms etc.) via PC, content as belows:
```sh
#!/bin/bash

sed -i '/NetworkInterfaceBlacklist/ s/wlan0,//' /etc/connman/main.conf
/etc/init.d/S08connman restart

exit
```

### Details of any modifications you have made to Knulli.

Nah

**Comment by Mikhailzrick** [comment]
You can just remove the wlan0 from the connman config and run batocera-save-overlay

**Comment by ben-willmore** [comment]
I also had this problem, but it is fixed by the 2024-10-02 alpha.

**Comment by ben-willmore** [comment]
I tried alpha build 20241002, and the wifi dongle doesn't work unless the above custom.sh is used.

**Comment by Mikhailzrick** [comment]
I redid some of the previous wifi stuff that was just temp fix until I had time for a better approach. Now there’s a new wlan manager that will loop through and only enable the first found wlan. This should take care of this issue as there’s no longer any hard coded wlan’s being blocked or disabled.
