### ISSUE TITLE
Smart Pro - Suspend

### ISSUE THREAD

**Issue by dopazz** [knulli-cfw/distribution#11]
### Knulli build version

40-dev-2ad15957a8 2024/04/30 02:57

### Your architecture

TrimUI Smart Pro

### Issue description

Weirdness when attempting to suspend: sometimes the console will freeze and reboot when I attempt to suspend.  Other times it will do nothing at all.  This behavior happens both by tapping the power button to suspend and also when using the Main Menu -> Quit -> Suspend System option.  

Suspend seems to always work perfectly the first time I try to use it after a reboot.  Subsequent attempts to suspend after a previous suspend->wake cycle cause problems.

### Detailed reproduction steps

1. Boot Smart Pro.
2. Enter suspend mode, either by tapping power or using menu option.
3. Wake Smart Pro.
4. Attempt to enter suspend mode, either by tapping power or using menu option.
5. Abnormal behavior occurs: either a failed suspend attempt that causes nothing to happen, or a failed suspend attempt that freezes and reboots.

### Details of any attempts to fix this yourself

Reported through Discord and directed to GitHub.

### Details of any modifications you have made to Knulli.

I tested handheld 'tate mode and the refactored artbook theme on this installed.

### Logs and data

let me know if you need the support tar.

**Comment by Mikhailzrick** [comment]
Issue resolved
