### ISSUE TITLE
Apple2 and Libretro:MAME not working.

### ISSUE THREAD

**Issue by dmmarti** [knulli-cfw/distribution#113]
### Knulli build version

40-dev-d3b52Of949 2024/07/21 02:26

### Your architecture

RG40XX H

### Issue description

When launching an Apple 2 game using Libretro:MAME, games do not launch and return to ES menu.

### Detailed reproduction steps

Setup fresh install, copy all required BIOS files over, copy a game to roms/apple2. Set emulator to Libretro:MAME and try to launch a game.

### Details of any attempts to fix this yourself

After creating my own system (new custom es_systems config and new entry in the messSystems.csv file - saved changes by running batocera-save-overlay), Apple2 games launch like they should.

I've narrowed the problem down to the embedded MAME(MESS) launch command arguments that Knulli/Batocera uses.

### Details of any modifications you have made to Knulli.

This file:
(https://github.com/batocera-linux/batocera.linux/tree/master/package/batocera/core/batocera-configgen/configgen/configgen/generators/libretro)
/libretroMAMEConfig.py 

Line 161 adds this hard-coded launch argument for Apple 2

commandLine += ["-sl7", "cffa202"]

This causes the RG40XX H to have some kind of issue and does not allow Retroarch to launch the game.  

As can be see in the es_launch_stderr.log file:

[libretro INFO] Starting game from cmd: "apple2ee -sl7 cffa202 -flop1 "/userdata/roms/apple2/Galaxian (Starcraft) (USA).dsk" -rompath /userdata/roms/apple2;/userdata/bios/ -ui_active -cfg_directory /userdata/system/configs/lr-mame/apple2ee/custom/ -inipath /userdata/saves/mame/mame/ini/ -artpath /var/run/mame_artwork/;/usr/bin/mame/artwork/;/userdata/bios/lr-mame/artwork/;/userdata/bios/mame/artwork/;/userdata/decorations/ -artwork_crop -pluginspath /usr/bin/mame/plugins/;/userdata/saves/mame/plugins -homepath /userdata/saves/mame/plugins/ -samplepath /userdata/bios/mame/samples/"

By removing this hard-coded command line argument, this fixes Apple2 using Libretro:MAME on the RG40XX H handheld.  Slot 7 is used for video card definitions in MAME(MESS) so I'm guessing this is causing some type of internal error within Retroarch.

**Comment by tsankuanglee** [comment]
Thank you, @dmmarti . This information helped me create a patch upstream https://github.com/batocera-linux/batocera.linux/pull/13058 .

`commandLine += ["-sl7", "cffa202"]` is an SD/IDE card, so it'll be expecting a hard disk image. You are correct that if you are running a floppy image, this should be removed.

**Comment by dmmarti** [comment]
Thank you @tsankuanglee .... I see it is now merged into batocera.

**Comment by dmmarti** [comment]
I'm closing this issue since the fix was merged upstream in batocera.

**Comment by pashdown** [comment]
@dmmarti could you post the details of your workaround? Since knulli still hasn't seen the changes necessary.

Specifically - _new custom es_systems config and new entry in the messSystems.csv file - saved changes by running batocera-save-overlay_
