### ISSUE TITLE
Files will fail after hitting around 1.3 gb

### ISSUE THREAD

**Issue by jhsmith0703** [knulli-cfw/distribution#114]
### Knulli build version

na

### Your architecture

rg35xx plus and rg35xx h

### Issue description

when downloading knulli on my laptop and phone, over both the rg35xx plus update file and the rg35xx h install file, the files would get to no more than 1.3 gb downloaded then fail every time. I have tried on my phone and laptop, and on various different private and public wifis

### Detailed reproduction steps

Press download - wait - download fails.

### Details of any attempts to fix this yourself

Change devices, change wifi

### Details of any modifications you have made to Knulli.

No

### Logs and data

No logs

**Comment by kibble42** [comment]
I'm having the same problem. Did you find a solution?

**Comment by Mikhailzrick** [comment]
It affects some people in Europe mostly, but not always. It’s something to do with GitHub. There is a torrent file link is on the main Knulli website. I’d suggest trying that.

**Comment by kibble42** [comment]
Got it working using FreeDownloadManager
