### ISSUE TITLE
Device wakes up from sleep when hinge is closed and power cable is attached/detached

### ISSUE THREAD

**Issue by joonaskokko** [knulli-cfw/distribution#115]
### Knulli build version

40-dev-d3b520f949 2024/07/20 19:50

### Your architecture

Anbernic RG35XX SP

### Issue description

The Anbernic SP wakes up from sleep when power cable is attached although the hinge is closed.

### Detailed reproduction steps

- Start any game, have volume up so you can hear music and sound
- Close the lid/hinge
- Note that the music/sound stops as the device goes to sleep
- Attach power cable to charge the device
- Hear the device wake up from sleep as game's sound starts to play although the lid/hinge is closed
- Open the lid/hinge, see that the display has turned on and then close it again to put the device back to sleep

### Details of any modifications you have made to Knulli.

No modifications.

**Comment by Mikhailzrick** [comment]
Issue is resolved. On the sp if waking from suspend and the lid is closed it will suspend again.

plugging the power cable in is a wake up event. Closing as issue is resolved.
