### ISSUE TITLE
Totallly unclear what or where to go

### ISSUE THREAD

**Issue by realjax** [knulli-cfw/distribution#12]
### Knulli build version

none

### Your architecture

rg35xx plus

### Issue description

I find it utterly confusing what the actual state is of batorcera for (in my case an rg35xx plus) my device.

let me clarify ( or mistify would be a better word)

There is this page:
https://github.com/rg35xx-cfw/rg35xx-cfw.github.io/releases

which seems to hold an intial build for my device, made somewhere in februari.

Then there is this page:
https://github.com/rg35xx-cfw/rg35xx-cfw.github.io/releases/tag/rg35xx_plus_h_batocera_20240306

which has an ( not yet stable) build of batocera 40, but made for the rg35xx

THEN there is this page
https://www.reddit.com/r/batocera/

which says, 'hey, have an rg35xx move to knulli for support!' (cause we wont apparently??)

And at knullie there is no support for the the thing whatseoever. All I can find is a release for an rg28xx ??

To be honest I'm much in favor of that early 40 build because that seems to be te most complete and compatible. But is the (future??) build at knullie based on that version or some another version?

So.. sorry If I came on a little strong, I dó very much appreciate the efforts you guys put in!! 👍 

 but what gives  ?????

### Detailed reproduction steps

-

### Details of any modifications you have made to Knulli.

-

**Comment by dsivesto** [comment]
https://github.com/knulli-cfw/distribution/issues/1 if you look here you'll see that rg35xx plus/h/2024 support is unfinished at present. Your options if you want it now are to donate to the ko-fi for early access or build an image from source, the latter I couldn't get to work, but ymmv

**Comment by acmeplus** [comment]
For all rg35xx-plus development, this is the place, you can find the first public release here: https://github.com/knulli-cfw/distribution/releases/tag/20240530

You can also read more about this in the documentation page: https://knulli.org
