### ISSUE TITLE
Wifi only connect to 2,5ghz

### ISSUE THREAD

**Issue by clode666** [knulli-cfw/distribution#15]
### Knulli build version

Knulli 20240517

### Your architecture

Trimui

### Issue description

First thanks for your hard work! Have issues for wifi connections.Only connect to 2,5ghz not on 5ghz.Thanks for your reply.

### Detailed reproduction steps

Try to connect wifi.

### Details of any modifications you have made to Knulli.

Clean install

**Comment by thatso** [comment]
The Trimui Smart Pro does not have 5 GHz Wifi. You can verify this with the stock firmware.
