### ISSUE TITLE
Commit a569ec1 breaks controls on trimui smart pro

### ISSUE THREAD

**Issue by petrm** [knulli-cfw/distribution#195]
### Knulli build version

any build after commit a569ec1

### Your architecture

TrimUI Smart Pro

### Issue description

Commit a569ec1 breaks controls on trimui smart pro. This commit changes [es_input.cfg](https://github.com/knulli-cfw/distribution/commit/a569ec1f572c5f845da300e00da1696039cc0d2a#diff-1cfc7a24cdc48dbc31c3cde5d2d08e973c0191d74a57e9f6ac204066715b3027). Reverting to previous version of the file makes controls operational again.

### Detailed reproduction steps

See description

### Details of any modifications you have made to Knulli.

Clean build from source before and after a569ec1.

**Comment by Mikhailzrick** [comment]
If you run evtest what’s the reported controller device name?

**Comment by Mikhailzrick** [comment]
I looked it up, it's TRIMUI Player1, but no change was made to that device's default input mappings so I'm not sure what change you are referring to.

**Comment by petrm** [comment]
I did a clean build before and after that commit and reverting those changes made the controls work. However, the latest release image also works, so I am closing the issue.
