### ISSUE TITLE
5GHz WiFi is Not Reliable on RG-CubeXX

### ISSUE THREAD

**Issue by bremedios** [knulli-cfw/distribution#197]
### Knulli build version

firefly 2024/12/02 13:42

### Your architecture

RG-CubeXX

### Issue description

WiFi can be unreliable on the RG-CubeXX when connected to a 5Ghz network.

TLDR: 5Ghz on RG-CubeXX is unreliable.  2.4GHz is reliable and no issues observed on the RG40XXV.

2.4GHz
- Reliable when restarting the system
- Reliable when shutting down the system
- Cannot reproduce any issues

5Ghz
- Doing a full shutdown and startup seems to have a high occurrence of the issue

5GHz getting the WiFi working
- Restarting does not clear the issue
- Full shutdown / restart does not clear the issue
- Sometimes it will show different SSIDs you can connect to, sometimes it will not
- Switching to a 2.4GHz network will resolve the issue (sometimes you need to reboot after doing this.)

### Detailed reproduction steps

1. Connect to 5GHz network with RG-CubeXX
2. Perform a full-shutdown then power the unit on
3. The WiFi will not connect

### Details of any attempts to fix this yourself

1. Restarting the system does not resolve the issue
2. Full shutdown / startup does not resolve the issue
3. Switching to a 2.4Ghz network resolve the issue but sometimes you need to reboot after that change

### Details of any modifications you have made to Knulli.

None, this is the downloaded alpha build.

**Comment by bremedios** [comment]
5 GHz Network Setup

- 5GHz A/N/AC
- WPA2 AES
- Channel Width: 80MHz
- MSDU Aggregation Disabled
- MPDU Aggregation Enabled

**Comment by bremedios** [comment]
Root Cause
- The enabling of wifi via "connmanctl enable wifi" is not always working and when "connmanctl scan wifi" is called you sometimes get a no carrier error.

Workaround:
- When you get the "No carrier" error from "connmanctl scan wifi" simply call "connmanctl enable wifi" / "connmanctl scan wifi" again.

**Comment by bremedios** [comment]
The No carrier is a little bit of a red herring.  It may be an issue, but it does not appear to be the only issue here.  Working through the no carrier issue does not result in a connection.

Attempting connection directly through connmanctl now, it seems to be having an issue accepting the passphrase.

**Comment by bremedios** [comment]
Some articles that may help

- https://wiki.archlinux.org/title/ConnMan#Troubleshooting
- https://wiki.ubuntu.com/ConnMan/Debugging

**Comment by bremedios** [comment]
### 2.4GHz Testing Results

- 100 Test iterations
- No occurrence of "No Carrier" error
- No failures to get IP address or reach www.google.com

Time from "S20connman restart" until having an IP Address

- Min: 7 seconds
- Avg: 19 seconds
- Max: 43
- Majority of time was in the 7 to 8 second or 36 to 38 second range.

**Comment by bremedios** [comment]
### 5GHz Testing Results

- 5 Test Iterations
- No occurrence of "No Carrier" error
- No failures to get IP address or reach www.google.com

Time from "S20connman restart" until having an IP Address

Min: 37 seconds
Avg: 37 seconds
Max: 38

**Comment by bremedios** [comment]
5 GHz Testing Results
- 100 Test Iterations
- No occurrence of "No Carrier" error
- No failures to get IP address or reach www.google.com

Time from "S20connman restart" until having an IP Address

- Min: 6 seconds
- Avg: 31 seconds
- Max: 39

**Comment by bremedios** [comment]
It has been observed that the SSID being connected to can be different than what is being shown by the UI under network settings.

**Comment by bremedios** [comment]
Tracked this down to the router where it would allow some 5GHz devices to connect and others to not connect. This made it a little more complicated to diagnose as many 5GHz devices (including an RG400XV) had no problems connecting and using the 5GHz network.

After rebooting the router, 5GHz is reliable enough on the RGCubeXX where it seems that I can no longer reproduce this.  The no carrier errors mentioned above may or may not have been related to this.

**Comment by standerksen** [comment]
@bremedios Can you explain what you have changed on your router? I am facing the exact same issue:
- RG CubeXX
- Issues with 5 GHz but not 2,4 GHz (5 GHz very rarely reconnects, but 2,4 GHz reconnects just fine after sleep and shutdown)
- S20connman shows "no carrier" errors

**Comment by bremedios** [comment]
All I did was rebooted it.  It was only selling to have this issue with this one device but I rebooted the router and the issue has not come back.

**Comment by ianfrank** [comment]
I am seeing the same issue on my RG CubeXX. After reboot it does not automatically connect to wifi, Internet Status : Not connected. 
If I then disable wifi and enable it again, it connects without issues.
