### ISSUE TITLE
Bluetooth Audio not working

### ISSUE THREAD

**Issue by ghost** [knulli-cfw/distribution#24]
### Knulli build version

40-dev-d8b86623f3 2024/05/30 01:50

### Your architecture

RG35XXH

### Issue description

Audio still plays on the H's speakers even though a bluetooth earphone is already connected. I'm using a Redmi Buds 3 Lite, if that helps.

Thank you for the great work, by the way. :)

### Detailed reproduction steps

1. Used the "Pair a bluetooth device manually" option.
2. Heard the audio cue for a successful connection from the earphone.
3. Earphone is listed under the "Forget a bluetooth device" option.
4. Got to the game list and the audio from the video preview played on the H's speaker.
5. Tried to open the game and the audio still played on the speaker.

### Details of any attempts to fix this yourself

- Tried to restart the device from the menu.
- Tried to turn off and on the device using the power button.
- Tried to turn off and on the bluetooth.
- Tried to forget the device and manually pair it again

### Details of any modifications you have made to Knulli.

Experiencing this issue from a fresh install. I've only mapped the controls before trying out the bluetooth audio.

**Comment by kj77** [comment]
Go to system settings and change the audio output.

**Comment by ghost** [comment]
Forgot to mention that I also did this and it didn't work.

Anyway, I had more time yesterday to test the bluetooth audio and I got my other devices to work (Redmi Buds 3 Pro, Haylou GT5, Logitech G435).

Probably just a weird incompatibility bug for that specific device on my original post.
