### ISSUE TITLE
HDMI Issues

### ISSUE THREAD

**Issue by DriftLegend** [knulli-cfw/distribution#29]
### Knulli build version

KNULLI V40-dev-d8b86623f3 2024/05/30 01:50

### Your architecture

RG35XXPLUS

### Issue description

If I connect RG35XX PLUS to a TV via HDMI from main menu and then use any emulator (NES, PSX, does not matter) then in about 1-10 minutes of gameplay something weird happens. The game plays fine, then KNULLI logo appears with loading bar and loads up main menu above my running game. The only way to really fix this issue is to unplug HDMI and restart the system, and then it will happen again. Happens 100% of the time. Never happened in batocera v40, that one just couldn't display HDMI for more than a minute at all...
Also, the system does not return to the device's screen if I unplug the HDMI, only reboot fixes the issue.

Here's a video demonstration of the issue!

https://youtu.be/LLuc2JVBh9M

Error happens at 3:05

### Detailed reproduction steps

1)Connect HDMI from main menu
2)Play any game for about 10 minutes
3)MAYBE switching games would help to reproduce the issue, however, it's not mandatory as it happens in any conditions

### Details of any attempts to fix this yourself

I tried connecting it to a modern tv instead of a vintage one with a converter. Error still happens.

### Details of any modifications you have made to Knulli.

None

### Logs and data

[wsdd.log](https://github.com/user-attachments/files/15522439/wsdd.log)

This is the only log file that is not empty

**Comment by Mikhailzrick** [comment]
Issue has been resolved
