### ISSUE TITLE
L/R not mapped

### ISSUE THREAD

**Issue by kthod861** [knulli-cfw/distribution#30]
### Knulli build version

knulli-h700-rg35xx-plus-40-20240530

### Your architecture

RG35XX PLUS, RG35XX H

### Issue description

Could not get L/R working ( for FZero and Locoroco as example ).
Found out es_input.cfg is missing them in "Deeplay-keys" input config but was unable to remap them using the remap tool.

Can this cfg file get an update please ?

### Detailed reproduction steps

try FZero or Locoroco

### Details of any attempts to fix this yourself

Copy/Pasted values found on internet, but really not sure its ok ( for the H in particular regarding the joysticks )

        <inputConfig type="joystick" deviceName="Deeplay-keys" deviceGUID="19000000010000000100000000010000">
            <input name="a" type="button" id="3" value="1" code="304" />
            <input name="b" type="button" id="4" value="1" code="305" />
            <input name="down" type="hat" id="0" value="4" />
            <input name="hotkey" type="button" id="11" value="1" code="312" />
            <input name="l2" type="button" id="13" value="1" code="314" />
            <input name="left" type="hat" id="0" value="8" />
            <input name="pagedown" type="button" id="8" value="1" code="309" />
            <input name="pageup" type="button" id="7" value="1" code="308" />
            <input name="r2" type="button" id="14" value="1" code="315" />
            <input name="right" type="hat" id="0" value="2" />
            <input name="select" type="button" id="9" value="1" code="310" />
            <input name="start" type="button" id="10" value="1" code="311" />
            <input name="up" type="hat" id="0" value="1" />
            <input name="x" type="button" id="6" value="1" code="307" />
            <input name="y" type="button" id="5" value="1" code="306" />
        </inputConfig>

**Comment by THFourteen** [comment]
Analogue sticks were not mapped on my RG35XXH either. I just went into settings - controllers and mapped the whole controller again, did you try that?

**Comment by kthod861** [comment]
Long story short i was dumb enough to not understand that north/south/east/west were buttons, not directions, this, blocking me from correctly setting up the mapping .
Now that's behind, everything is ok on the H.
I may close this even if out of the box the cfg is not correct ?

**Comment by MrFobs1** [comment]
I also have this problem on the rg35xx plus. L and R do not work in PPSSPP and I can not map them because they are not recognized when I try to map them. This appears to happen in all games. I have tested 5 with the same results.

EDIT: I was able to fix this by going to Settings > Controller/Bluetooth > Remap controls. You have to hold one of the buttons to start mapping and the shoulder ander trigger buttons are flipped, but once I remapped each key manually they appear to work now!

**Comment by Mikhailzrick** [comment]
Issue resolved.
