### ISSUE TITLE
Share partition not mountable on macOs

### ISSUE THREAD

**Issue by 2kohm** [knulli-cfw/distribution#34]
### Knulli build version

40-dev-d8b86623f3 2024/05/30 01:50

### Your architecture

RG35XXH

### Issue description

Data / share partition is not mountable on macOs.
SD CARD = 256GB
was working fine in the v39

Model: sun50iw9
System: Linux 4.9.170
Architecture: aarch64
Board: rg35xx-plus
CPU Cores:  / CPU Threads: 4
CPU Max Frequency: 1512 MHz
Temperature: 55°C
Available Memory: 730/973 MB
Display Resolution: 640x480
Display Refresh Rate: .Hz
Data Partition Format: ext4
Data Partition Available Space: 217G
OS version: 40-dev-d8b86623f3 2024/05/30 01:50

### Detailed reproduction steps

flashed KNULLI with raspberryPi imager.
TF-SLOT1
knulling is booting fine everything is working fine, no errors during installation / disk expansion.
put sd card in Mac (Mac m2 Sonoma 14.5 )
BATOCERA partition is there but no share partition.
i can transfer data via /userdata/roms

### Details of any attempts to fix this yourself

also on 32GB SD card, same issue 

### Details of any modifications you have made to Knulli.

stock

**Comment by DriftLegend** [comment]
Read FAQ before posting.

https://knulli.org/play/add-games/

As explained above, the SHARE partition is formatted to ext4 by default. Therefore, it is not accessible on Windows (macOS for you). However, if neither network transfer nor a Linux computer is available to you, there are options to access the SD card from Windows anyway.

It is possible to reformat the SHARE partition to exFAT, to make the partition accessible on Windows. To format the partition to exFAT anyway, open the KNULLI main menu by pressing Start and choose Format a disk in the Frontent developer options section of the System settings. You will be able to choose whether you want your partition formatted to ext4 or exFAT.

Hope that solves your issue.

**Comment by 2kohm** [comment]
many thanks @DriftLegend
