### ISSUE TITLE
Volume level resets every reboot

### ISSUE THREAD

**Issue by symbuzzer** [knulli-cfw/distribution#38]
### Knulli build version

20240530

### Your architecture

RG35XX PLUS

### Issue description

Volume level resets every reboot

### Detailed reproduction steps

Set volume to specific value from buttons and reboot.  

### Details of any attempts to fix this yourself

-

### Details of any modifications you have made to Knulli.

-

**Comment by radsutton** [comment]
I also have this issue on RG35XX-H and RG28XX.
