### ISSUE TITLE
Battery level indicator issues

### ISSUE THREAD

**Issue by symbuzzer** [knulli-cfw/distribution#41]
### Knulli build version

20240530 

### Your architecture

RG35XX PLUS

### Issue description

1) Level doesnt change when charging in off-mode

2) I can play nearly one more hour when it is %0

### Detailed reproduction steps

1) Plug charger when device off and wait. Battery level doesnt change

2) Play games when it reachs %0

### Details of any attempts to fix this yourself

-

### Details of any modifications you have made to Knulli.

-

**Comment by Mikhailzrick** [comment]
Issue was determined to be in ES, anything less than 10% would incorrectly display as 0%. Upstream fix should be available soon.

**Comment by symbuzzer** [comment]
@Mikhailzrick Any ETA for public update?

**Comment by Mikhailzrick** [comment]
No ETA at this time.
