### ISSUE TITLE
Stereo Audio Not Working

### ISSUE THREAD

**Issue by varoudis** [knulli-cfw/distribution#49]
### Knulli build version

multiple (official and git builds)

### Your architecture

H700 - RG35XX H

### Issue description

The RG35XXH does not play stereo audio.

### Detailed reproduction steps

I tested with generated wav/mp3 from Ableton. Everything is mixed to mono.
Internal speakers and headphones.

Official OS works with stereo files.

### Details of any modifications you have made to Knulli.

no mods

**Comment by Mikhailzrick** [comment]
Issue is known, fix should be in future builds.

**Comment by MicAPic** [comment]
Saw this being fixed in [20240721](https://github.com/knulli-cfw/distribution/releases/tag/20240721) changelogs... and, well, it pretty much wasn't. At least the issue persists on RG35XXSP.

**Comment by Mikhailzrick** [comment]
Issue is resolved.
