### ISSUE TITLE
Can't change N64 controls and no bindings for C Buttons L+D

### ISSUE THREAD

**Issue by NathanUrwin** [knulli-cfw/distribution#52]
### Knulli build version

20240530

### Your architecture

RG35XXSP

### Issue description

I'd like to change the controls for N64, but the mupen config is overwritten whenever you start up a game. There's also no bindings for the C left and down buttons.

### Detailed reproduction steps

1. Flashed with balena etcher
2. Setup wifi
3. Connected with windows explorer
4. Copied over N64 roms
5. Opened `\\KNULLI\share\system\configs\mupen64\mupen64plus.cfg` with notepad
6. Edited controls
7. Saved config file
8. Started N64 game
9. `\\KNULLI\share\system\configs\mupen64\mupen64plus.cfg` overwritten with defaults

### Details of any attempts to fix this yourself

I tried restarting and shutdown/startups but that didn't help

### Details of any modifications you have made to Knulli.

None

**Comment by NathanUrwin** [comment]
Work around for now is changing the emulator to a libretro one. I had better performance with Parallel N64 with the games I was playing, LOZOOT & SM64

START Button > GAME SETTINGS > SYSTEM SETTINGS / PER SYSTEM ADVANCE CONFIGURATION > Nintendo 64 > EMULATOR > LIBRETRO: PARALLEL N64

**Comment by paronowitz** [comment]
You have to edit the input.xml file under system/configs/mupen64 not the mupen64plus.cfg file. This is documented on the official batocera page which this is a fork of

**Comment by NathanUrwin** [comment]
> You have to edit the input.xml file under system/configs/mupen64 not the mupen64plus.cfg file. This is documented on the official batocera page which this is a fork of

ahhh gotcha, thanks for the heads up! heres the link to the batocera docs if it helps anyone in the future: https://wiki.batocera.org/systems:n64#remapping_for_standalone_mupen64plus
