### ISSUE TITLE
Bluetooth is not working properly

### ISSUE THREAD

**Issue by mime29** [knulli-cfw/distribution#65]
### Knulli build version

Release 20240530

### Your architecture

RG35XX H

### Issue description

What did I try?

To connect a [PS4 Controller](https://www.playstation.com/en-us/accessories/dualshock-4-wireless-controller/) to the device. 
Play game with it.

### Detailed reproduction steps

Steps: 
- Turn on the device
- Go to Controller and Bluetooth menu
- Turn the PS4 controller into pairing mode SHARE + PS (long time until it blinks very rapidly)
- Add device manually
- The list of BT devices started to appear
- I selected the controller and it was connected!
- Success: I can control the UI with the controller.

Problems:

many problems encountered from there:

1. If I turn off bluetooth and turn it back on, the device is not reconnecting even when pressing the PS button.

Then

1. If I try to repair the device manually, the list shows only the controller, no other devices anymore.
2. If I select the controller in this same menu, it keeps doing "please wait"
3. If I try to remove the device, it works but then, impossible to add it back from the add manually menu anymore

Then

1. If I pair it successfully, I launch a game (I think it was a megadrive one), the controller was not responding. anymore. (Maybe there is something to do to access the emulator config or something, I don't know at that point, ideally, BT controller should be configured automatically in emulators but I imagine it's hard to do)

### Details of any attempts to fix this yourself

The hack-fix:

I simply had to restart the device to be able to pair the controller again.

Other point: If there is a way to play with 2 players with 2 PS4 BT controllers, that would be nice to have a little wiki tutorial about this really nice feature.

### Details of any modifications you have made to Knulli.

None.

### Logs and data

No logs but If something is necessary, I can provide.

**Comment by Mikhailzrick** [comment]
I believe this is related to a bug in batocera. I’m fairly confident the issue is resolved since this issue was reported. I am able to connect several of my Bluetooth controllers without issue.
