### ISSUE TITLE
Shader Settings Not Saving

### ISSUE THREAD

**Issue by dji85** [knulli-cfw/distribution#68]
### Knulli build version

40-dev-b9b717e246 2024/06/08 22:54

### Your architecture

RG35XX SP

### Issue description

Shader Settings Not Saving

### Detailed reproduction steps

I can’t make shader settings save on Knulli , tried saving core or content directory overrides and saving shader presets for core or content directory but even if I select the same game again the shader setting disappears. The specific shader preset I am trying is handheld/lcd3x.glslp.

### Details of any modifications you have made to Knulli.

N/A

**Comment by IronbugVR** [comment]
You have to go to advance system options first, (press select in system folder) and set shaders to none. Now when you set your shaders in retroarch and save them it will be there the next time you launch a game.

**Comment by Mikhailzrick** [comment]
Issue resolved.

**Comment by Manddrakke** [comment]
Have same problem but when i set shaders to nono the emulation are to fast!

RG35XX Plus / Knulli
