### ISSUE TITLE
Memory Leak on RG35XXH still going

### ISSUE THREAD

**Issue by Akamilad** [knulli-cfw/distribution#69]
### Knulli build version

40-dev-d8b86623f3 2024/05/30 01:50

### Your architecture

RG35XXH

### Issue description

RAM is still decreasing, even without doing anything, until it reaches 0 Mo and totally freezes. Knulli will reload itself in a couple of minutes after and starts with around 640 Mo free ouf of 1Go and decrease again. It's a loop.

### Detailed reproduction steps

I installed Knulli on SanDisk SD Cardwith Rufus v4.5, powered on the RG35XXH, add games + BIOS through SMB share folder and that's all.

### Details of any attempts to fix this yourself

I tried to reboot the device, format the SHARE partition into exFAT, but it does the same.

### Details of any modifications you have made to Knulli.

None.

### Logs and data

None.

**Comment by HoroTW** [comment]
Hi there,

I was trying to reproduce the issue on a RG35XXH on the new release [20240721](https://github.com/knulli-cfw/distribution/releases/tag/20240721) (40-dev-d3b520f949).

I booted the system and after a few minutes (~5-10) I looked at the `System Settings` -> `Information`.
I had 756/973 MB available.

After half an hour, no restart of Knulli or EmuStation and still 756/973 MB available.

Can you reproduce it or can we consider this as solved?

~Horo

**Comment by Akamilad** [comment]
Hi HoroTW,

I tested the new 20240721 and it seems that the issue is now solved. I can close the issue ticket.

**Comment by Akamilad** [comment]
Issue solved with the 20240721 release.
