### ISSUE TITLE
Fbneo on rg28xx

### ISSUE THREAD

**Issue by khaleelnajjar** [knulli-cfw/distribution#77]
### Knulli build version

2024/05/09

### Your architecture

RG28XX

### Issue description

Fbneo and Fbalpha don't work if you launch the game from the front end, but if you manage to launch the game from inside RetroArch using the Fbneo core, it works fine. 

### Detailed reproduction steps

N/A

### Details of any modifications you have made to Knulli.

None. Installed knulli as is

**Comment by bladeoner** [comment]
Hi did you try the latest build?

**Comment by khaleelnajjar** [comment]
Yes, latest build solved the problem.

**Comment by bladeoner** [comment]
Good to hear, I would suggest to close the issue.
