### ISSUE TITLE
Drastic controls don’t work in config overlay

### ISSUE THREAD

**Issue by gregdeveloper** [knulli-cfw/distribution#8]
### Knulli build version

2024/05/01

### Your architecture

RG35XXH

### Issue description

If you play a NDS game using drastic, you can bring up the configuration overlay with the hotkey combination, but when you’re there none of the buttons work apart from the dpad. This means you can’t change any settings and I couldn’t actually get out of it without rebooting the device.

### Detailed reproduction steps

Play an NDS game using drastic and pull up the configuration overlay with hotkey a or hotkey b, can’t remember which one. Then try to select any setting.

### Details of any modifications you have made to Knulli.

N/A

**Comment by gregdeveloper** [comment]
I found out that the volume buttons do the select and back in the drastic menus for now. Not ideal but means it's usable.

**Comment by bladeoner** [comment]
Hi @gregdeveloper, did you try the latest build?

**Comment by gregdeveloper** [comment]
> Hi @gregdeveloper, did you try the latest build?

Just got round to updating. Seems fine now. Only thing I did notice is that up on the analog doesn't go up in the drastic menu, whereas down goes down as expected. Dpad is fine though and the rest of the buttons seemingly.

**Comment by Disttrack** [comment]
All fine except when I enter in cheats menu, I cant go back. Any solution? RG35XXH too.

**Comment by Mikhailzrick** [comment]
Closing as it’s been resolved
