### ISSUE TITLE
[handheld tate mode] not working

### ISSUE THREAD

**Issue by al3x52** [knulli-cfw/distribution#87]
### Knulli build version

40-dev-d3b520f949 2024/07/21 02:18

### Your architecture

RG35XX H

### Issue description

Hello, thanks for the firmware !

but the `handheld tate mode` doesn't seem to work in the latest version `20240721`.

The game just run in 'normal' mode :
- no screen rotation
- no right stick mapping

It works in the previous version `20240530`

### Detailed reproduction steps

- set `handheld tate mode` to `on `via `fbneo` system menu (or add `fbneo.fbneo-hhtate=True` to `batocera.conf`)
- launch any games from `vertical arcade` auto collection or directly from `fbneo` system (ex: 1942.zip, batsugun.zip, ...)

expected result :
- screen rotated 90° counter clockwise
- right stick mapped

actual result :
- no screen rotation
- no right stick mapping

### Details of any modifications you have made to Knulli.

no modification, just set `handheld tate mode` to `on` via system menu

**Comment by DiegoBM** [comment]
Same problem using the anbernic rg35xx h. Is there any way to fix this in config?

**Comment by Mikhailzrick** [comment]
I redid a lot of the code regarding this feature. It should be working fine in the next public build.

closing as issue is resolved.

**Comment by DiegoBM** [comment]
Thank you @Mikhailzrick! Looking forward to trying it out. Any plans for a new release soon?

**Comment by Mikhailzrick** [comment]
> Thank you @Mikhailzrick! Looking forward to trying it out. Any plans for a new release soon?

Still working out a few bugs here and there in the alphas but there’s getting fewer and fewer bug reports after each alpha so we’re getting close.

**Comment by DiegoBM** [comment]
Awesome news!

Do you have by any chance, any documents on how to build and test the alphas on the actual device? If you don't it's cool, I'm just kinda new to this world and trying to get up to speed. Thank you in any case for your incredible job!
